### ISSUE TITLE
Error : `KIN_AMAGAMBO.tandukanya()` method issue

### ISSUE THREAD

**Issue by FADHILI-Josue** [kin-lang/kin#41]
**Describe the bug**
issue when using the KIN_AMAGAMBO  tandukanya method.
i am getting objects array instead of array of strings

**To Reproduce**
1. make file try.kin
2. add codes `tangaza_amakuru(KIN_AMAGAMBO.tandukanya("hello world", " "))`
3. run `kin run ./try.kin`
5. See result ([object Object])

**Expected behavior**
expected to get a string array.

**Screenshots**
<img width="950" alt="image" src="https://github.com/kin-lang/kin/assets/117774073/51240988-918d-4956-b229-95053416795e">

**Comment by pacifiquem** [comment]
This is not a bug @FADHILI-Josue !!
Arrays in Kin are Objects.

So `KIN_AMAGAMBO.tandukanya("Hello World", " ")`, will produce an array of 2 elements: `Hello` `World`.
If you print it, you'll receive `[Object Object]` since `KIN_AMAGAMBO.tandukanya() is returning an array and an array is an object in Kin`.

In other to understand this try to run these codes:

`reka amagambo = KIN_AMAGAMBO.tandukanya("Kinyarwanda ni", " ")`
`tangaza_amakuru(amagambo[0]) # this will print Kinyarwanda`
`tangaza_amakuru(amagambo[1]) # this will print ni`

So this is the behaviour of our language.
